[package]
name = "langc"
description = "Lang.P compiler CLI"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "langc_cli"
path = "src/lib.rs"

[[bin]]
name = "langc"
path = "src/main.rs"

[dependencies]
langp-lexer = { workspace = true }
langp-ast = { workspace = true }
langp-parser = { workspace = true }
langp-semantic = { workspace = true }
langp-interpreter = { workspace = true }
langpm = { path = "../langpm" }
