[package]
name = "langp-interpreter"
description = "Tree-walking interpreter for Lang.P"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
langp-lexer = { workspace = true }
langp-ast = { workspace = true }
langp-runtime = { path = "../runtime" }

[lib]
name = "langp_interpreter"
path = "src/lib.rs"

[dev-dependencies]
langp-parser = { workspace = true }
langp-semantic = { path = "../semantic" }

[[test]]
name = "collections"
path = "tests/collections.rs"
